"""
This type stub file was generated by pyright.
"""

from .sequence import Sequence as Sequence, it as it, seq as seq, sequence as sequence

"""
This type stub file was generated by pyright.
"""
__ALL__ = ...
