"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator, Tuple
from .transform import T, Transform

class CombinationTransform(Transform[T, Tuple[T, ...]]):
    """
    A transform that yields all possible combinations of n elements from the input iterable.
    """
    def __init__(self, iter: Iterable[T], n: int) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[Tuple[T, ...]]:
        ...
    


