"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator
from .transform import T, Transform

"""
This type stub file was generated by pyright.
"""

class ConcatTransform(Transform[Iterable[T], T]):
    """Concatenate multiple iterables into a single iterable."""
    def __init__(self, iter: Iterable[Iterable[T]]) -> None: ...
    def __do_iter__(self) -> Iterator[T]: ...
