"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Iterable, Iterator, List, Optional
from .transform import T, Transform

class DedupTransform(Transform[T, List[T]]):
    """
    A transform that groups consecutive duplicates from an iterable.
    """
    def __init__(self, iter: Iterable[T], key_selector: Optional[Callable[[T], Any]] = ...) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[List[T]]:
        ...
    


