"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Iterable, Iterator, Optional
from .transform import T, Transform

"""
This type stub file was generated by pyright.
"""

class DistinctTransform(Transform[T, T]):
    """
    A transform that removes duplicates from an iterable.
    """
    def __init__(
        self, iter: Iterable[T], key_selector: Optional[Callable[[T], Any]] = ...
    ) -> None: ...
    def __do_iter__(self) -> Iterator[T]: ...
