"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator
from .transform import T, Transform

class DropTransform(Transform[T, T]):
    """A transform that drops the first n elements of an iterable."""
    def __init__(self, iter: Iterable[T], n: int) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[T]:
        ...
    


