"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator
from .transform import T, Transform

class DropWhileTransform(Transform[T, T]):
    """A transform that drops elements from an iterable while a predicate is true."""
    def __init__(self, iter: Iterable[T], predicate: Callable[[T], bool]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[T]:
        ...
    


