"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator
from .transform import T, Transform

class FilteringTransform(Transform[T, T]):
    """Transform that filters elements based on a predicate"""
    def __init__(self, iter: Iterable[T], predicate: Callable[[T], bool]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[T]:
        ...
    


