"""
This type stub file was generated by pyright.
"""

from typing import Callable, Generic, Iterable, Iterator, NamedTuple
from .transform import K, T, Transform
from .list_like import ListLike

class Grouping(NamedTuple, Generic[K, T]):
    key: K
    values: ListLike[T]
    ...


class GroupingTransform(Transform[T, Grouping[K, T]]):
    """
    A transform that groups elements of an iterable by a key function.
    """
    def __init__(self, iter: Iterable[T], key_func: Callable[[T], K]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[Grouping[K, T]]:
        ...
    


