"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator
from .transform import T, Transform

class IntersectionTransform(Transform[Iterable[T], T]):
    """A transform that yields the intersection of iterables."""
    def __init__(self, iter: Iterable[Iterable[T]]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[T]:
        ...
    


