"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator
from .transform import T, Transform, U

class MappingTransform(Transform[T, U]):
    """A transform that applies a function to each element of an iterable."""
    def __init__(self, iter: Iterable[T], transform: Callable[[T], U]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[U]:
        ...
    


