"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator
from .transform import O, T, Transform, U

class MergingTransform(Transform[T, U]):
    """
    Merges two iterables into a single iterable by applying a transformation function to each pair of elements.
    """
    def __init__(self, iter: Iterable[T], other_iter: Iterable[O], transform: Callable[[T, O], U] = ...) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[U]:
        ...
    


