"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator
from .transform import T, Transform, U

"""
This type stub file was generated by pyright.
"""

class MergingWithNextTransform(Transform[T, U]):
    """
    Transforms an iterable by applying a function to each element and the next element.
    """
    def __init__(self, iter: Iterable[T], transform: Callable[[T, T], U] = ...) -> None: ...
    def __do_iter__(self) -> Iterator[U]: ...
