"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterable, Iterator, Literal, Optional
from .transform import T, Transform, U

"""
This type stub file was generated by pyright.
"""

class ParallelMappingTransform(Transform[T, U]):
    """A transform that applies a function to each element of an iterable in parallel."""

    Executor = Literal["Thread", "Process"]
    def __init__(
        self,
        iter: Iterable[T],
        transform: Callable[[T], U],
        max_workers: Optional[int] = ...,
        chunksize: int = ...,
        executor: ParallelMappingTransform.Executor = ...,
    ) -> None: ...
    def __do_iter__(self) -> Iterator[U]: ...
