"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator, Union
from random import Random
from .transform import T, Transform

class ShufflingTransform(Transform[T, T]):
    """
    A transform that shuffles the elements of an iterable.
    """
    def __init__(self, iter: Iterable[T], random: Union[Random, int, float, str, bytes, bytearray, None] = ...) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[T]:
        ...
    


