"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator
from .transform import T, Transform

"""
This type stub file was generated by pyright.
"""

class TakeTransform(Transform[T, T]):
    """A transform that takes the first n elements of an iterable."""
    def __init__(self, iter: Iterable[T], n: int) -> None: ...
    def __do_iter__(self) -> Iterator[T]: ...
