"""
This type stub file was generated by pyright.
"""

import sys
from typing import Callable, Iterable, Iterator, TypeGuard
from .transform import T, Transform, U

if sys.version_info < (3, 10):
    ...
else:
    ...
class TypeGuardTransform(Transform[T, U]):
    """A transform that applies type guard to each item of the iterable."""
    def __init__(self, iter: Iterable[T], type_guard: Callable[[T], TypeGuard[U]]) -> None:
        ...
    
    def __do_iter__(self) -> Iterator[U]:
        ...
    


