"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Iterator, List
from .transform import T, Transform

"""
This type stub file was generated by pyright.
"""

class WindowedTransform(Transform[T, List[T]]):
    """
    A transform that yields windows of a given size from an iterable.
    If partial_windows is True, then windows that are smaller than the given size are yielded.
    If partial_windows is False, then only windows that are exactly the given size are yielded.
    """
    def __init__(self, iter: Iterable[T], size: int, step: int, partial_windows: bool) -> None: ...
    def __do_iter__(self) -> Iterator[List[T]]: ...
